record Error
    func constructor(self, what?)
        self.what? = what?
        return self
    end
end

func umm()
    raise Error("test")
end

func B()
    try
        1+umm()
    case Int
        print("no")
    end
    return 2
end

1 + B()
